travis:
  secure:
    BINSTAR_TOKEN: SMZodgx+SCa6QlH2hhNXBNrJwkSQfaIk++C3JXL6+GWhrqohepJp1QpftGjuhyj4DuJtOmmDoEzHO2rnya0u9auC5iKwWsfvpBzMScyAhdmfofY8yszMlngUQ4a/F/YFUj+gXEkSChf49YHkUY84TTOgHgTvtwV234vUgWd7gEPpqX1eQ+hZ1LFDbBkBaGpvND0yrLXG4oTyhryV1Das4C/FQ7rjVKNaa0j7TkwNnOLGJHLNH2OiPrnRq5uNxV6tzxIox8Wwxne1WpPmTMIoK4JKPNpLyZHLrmp8vYVEd+Z0YsIugHUwftHB5MhN2ZlG3mWrww66P2dt9eZY6Tg2EofAV9/Jm4a8ardLNi8RFhYgixO8i4cKjqdtSxOcW5ZVgsi2ECf45UsohyFeYsow9wc1EsqMll/HEOTQ6PjrJ33TZfzZD5L2rVq9qM91rf2SWR+5V5MMjiH8aQXZ8fivCXv8IN/ywkk7a9HFc8vviuuYOkhrLYCnllOkrGdX81BBCDQh8NQuUfC1Vus+4rd3r4CXkjVEzw4GQOcxN/CfElVvqcZV/e6HD03QaL5/b4G0yvLbrT0NZ1OT34nIRvpqK6rNiO3Xs7YEN6XVtk3LB6wRxheQ+cXyozP/bhE/tm8pHAxzM2iTi4LOB8YpXBH3T4L0867OoTZUkrzhzsC0j+E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
